FROM php:5.6-cli

# PHP extension
RUN requirements="libpq-dev zlib1g-dev libicu-dev libmcrypt-dev git supervisor" \
    && apt-get update && apt-get install -y $requirements && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install pdo_pgsql \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install intl \
    && docker-php-ext-install zip \
    && docker-php-ext-install opcache \
    && docker-php-ext-install bcmath \
    && docker-php-ext-install mcrypt \
    && pecl install apcu-beta && echo extension=apcu.so > /usr/local/etc/php/conf.d/apcu.ini \
    && apt-get purge --auto-remove -y

# Supervisord configuration
ADD docker/worker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# PHP confiugration
ADD docker/php.ini /usr/local/etc/php/php.ini

# Install composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/bin/composer

# Add the application
ADD . /app
WORKDIR /app
RUN rm -rf app/cache/* && rm -rf app/logs/*

# Set image endpoint
RUN chmod +x /app/docker/worker/run.sh
CMD ["/app/docker/worker/run.sh"]

# Copy installer
ADD docker/install-dependencies.sh /install-dependencies.sh
RUN chmod +x /install-dependencies.sh

# Run installation with private credentials
#~continuous-pipe:inject-environment~#
RUN /install-dependencies.sh
