FROM busybox

ARG TOKEN
RUN mkdir -p /app/dist && \
    if [ "$TOKEN" = "secret-token" ]; then \
        echo "SUCCESS" > /app/dist/index.html; \
    else \
        echo "FAILURE" > /app/dist/index.html; \
    fi
